### ISSUE TITLE
Conjoining an element to a list - context implies reversed operation

### ISSUE THREAD

**Issue by draeath** [functional-koans/clojure-koans#110]
In [koans.03-lists](/functional-koans/clojure-koans/blob/master/src/koans/03_lists.clj#L26), it appears (based on context) the intent is for the user to enter `'(:a :b :c :d :e)` as in the puzzle preceding it. However, conjoining to a list [prefixes, rather than suffixes](https://clojuredocs.org/clojure.core/conj). Eg, the actual solution would be `'(:e :a :b :c :d)` instead.

This appears to be unintentional, and might stand to use a different sequence than the prior puzzle or perhaps some rewording to 'break' the incorrect implication?

**Comment by trptcolin** [comment]
Correct, `conj`ing to a list adds to the left side, and `conj`ing to a vector adds to the right side, and it'll show you that there's an error if you try `'(:a :b :c :d :e)` as the answer. I like the fact that guessing based on context gives the wrong answer sometimes, and it was definitely intentional in this case, because it forces people to slow down and really make sure they understand what's happening. I don't want these exercises to be super-difficult, but I also want people to be surprised occasionally. Make sense?

**Comment by draeath** [comment]
Yes! The same kind of thing where a multiple-choice answer key might have a short pattern of repetition - you'd intentionally break that pattern so the taker couldn't just follow the pattern but would have to actually think about the problem. Good thinking :D
