### ISSUE TITLE
13_creating_functions.clj (has a bug?)

### ISSUE THREAD

**Issue by IrSent** [functional-koans/clojure-koans#120]
```
"Don't forget: first things first"
  (= [__ __ __ __]
       (let [ab-adder (partial concat [:a :b])]
       (ab-adder [__ __])))
```

Using `http://clojurescript.net/` REPL
that expression returns an Array `(:a :b __ __)`,
and not a Vector `[:a :b __ __]` as it is stated in the koan `(ab-adder [__ __ __ __])`

[clojure.core/concat documentation](https://clojuredocs.org/clojure.core/concat)

It would be a Vector if we add `into []`:
```
(into [] (concat [:a :b] ["a" "b"]))
```

**Comment by trptcolin** [comment]
Right, so this is a pretty common idiom in Clojure. When we compare using `=`, `[:a, :b :c]` is the same as `'(:a :b :c)`, which is the same as `(cons :a '(:b :c))`, etc. - even though those are all different concrete types (`clojure.lang.PersistentVector`, `clojure.lang.PersistentList`, and `clojure.lang.Cons`, respectively). The equality comparison doesn't care about the type, just the values contained in the sequential collection. And vector is a commonly used literal, in part since unlike the list literal, you don't have to worry about quoting.
