### ISSUE TITLE
Koans for testing, Koans for agents

### ISSUE THREAD

**Issue by equwal** [functional-koans/clojure-koans#150]
I think it would be nice to add Koans for generative tests with `tests.generative` after the metadata koans, and event-driven agent koans after the other reference type koans.

What do we think about such a thing? Should I go write some up? I'm planning on using Stuart Halloway's "Programming Clojure" as inspiration for the docstrings and pathology of ideas.

**Comment by equwal** [comment]
On the other hand, some might find them esoteric. I think Clojure's support for strong, simple test frameworks is one of its high points, however, and thing it might be useful even for beginners.

Likewise, Clojure's access to the JVM and ease of use makes it a really good choice for event-driven applications and GUIs. Other lisps are not so prepared for this use case.

**Comment by trptcolin** [comment]
Koans for agents would be good. 👍 

I think koans for `test.generative` or `test.check` would be cool too, but probably belong in a separate project (since this one is specifically dedicated to core clojure). There are [a small handful of other projects of koans using other libraries](https://github.com/functional-koans/clojure-koan-engine/wiki/Projects-using-the-koan-engine), which could be a good guide. 

Some `clojure.test` koans in this project could be an interesting proving ground for the testing idea, and I agree it's an important topic it'd be good to introduce to folks. It's kind of unclear to me how these would work though - since the koan runner itself is also kind of a test suite, there'd need to be some thought around how the expectations/blanks-to-fill-in are set up.
