### ISSUE TITLE
koans 19 datatypes, last meditation solution

### ISSUE THREAD

**Issue by fmesnata** [functional-koans/clojure-koans#154]
Since I couldn't find the solution for the last meditation of the datatype koan, I checked the solution and I was a bit suprised to find only :
```clojure 
(str "Congratulations on your Best Picture Oscar, "
                          "Evil Alien Conquerors!")
``` 
So we shouldn't use ``category`` and  ``recicpient`` here?

With auto-completion, I found this solution : 

```clojure 
(print (str "You're really the "
                (.-category this) ", "
                recipient
                "... sorry."))
``` 
Shouldn't it  be the solution here? 
Do the explaination for ``.-`` syntax comes later?

**Comment by trptcolin** [comment]
Ah, I see where the confusion is: those solutions aren't in order of the koans that are presented - they're in the order of the *blanks in the file*. So the solution you're looking for to solve that last koan in the file corresponds to [the first blank in that file](https://github.com/functional-koans/clojure-koans/blob/d749795c314baa9041b91b5915c0bb1a188521d1/resources/koans.clj#L212-L215), which is really similar to what you have there, except using `.category` instead of `.-category`. FWIW I don't think I've ever used the `.-category` syntax in JVM Clojure (though I recall doing that in ClojureScript).
