### ISSUE TITLE
10 Lazy Sequences - "Iteration can be used for repetition" not clear

### ISSUE THREAD

**Issue by telekid** [functional-koans/clojure-koans#75]
Before "Iteration can be used for repetition," a step should be added that introduces the concept of iterator partials. As it stands, this step cannot be completed by a clojure neophyte (like myself) without diving into the documentation, which seems to run contrary to the clojure koans process.

**Comment by rpazyaquian** [comment]
I am also having trouble with this one. Judging from the prior example, I expect that I have to pass in a function that just returns `:foo`. My attempts looked something like:

```
(take 100 (iterate (fn [x] x) :foo))
(take 100 (iterate #(%1) :foo))
(take 100 (iterate repeat :foo))
(take 100 (iterate str :foo))
```

The way it's presented, `iterate` infinitely and recursively applies that function to the argument passed in, e.g. `str` would result in this:

```
(:foo ":foo" ":foo" ":foo" ":foo" ":foo" ":foo" ":foo" ":foo" ":foo")
```

What we *actually* want is this, the result of (repeat 100 :foo):

```
(:foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo :foo)
```

What function applied to `:foo` just returns `:foo`? The way I solved it involved casting `:foo` to a keyword, which doesn't really make sense in a real-world context and is redundant anyway - so it feels like a hacky solution.

I don't think the question itself is bad, but it does require knowledge of a function that has not been introduced in prior koans. That throws the user off.

**Comment by trptcolin** [comment]
@rpazyaquian it looks like your first attempt ought to have worked actually! `(fn [x] x)` is a function that, given `:foo`, will return `:foo`. Incidentally, that function is the same as `identity`. The second one doesn't, because it'll try to use `:foo` itself as a function with 0 arguments (a bit of a limitation in the `#()` syntax).

Does that make sense? Anything you can think of that'd make it clearer for folks? Maybe we need to add a few warm-ups where part of the function passed to `iterate` is already filled in? I'd love a PR if you want to suggest something!

**Comment by rpazyaquian** [comment]
The way this is currently set up, the difficulty is not in figuring out what `iterate` does, but in figuring out what sort of function passed in to `iterate` would result in what we want. I feel like that distracts from the intent of the exercise, because it's not actually about `iterate` at that point.

`identity` did occur earlier in the koans, but as an aside, just being used in one of the exercises. It wasn't the focus of the exercise, so it doesn't necessarily stick out in the reader's mind.

**Comment by trptcolin** [comment]
@rpazyaquian What do you suggest we should do? I found `iterate` to be a tricky function to wrap my head around, specifically figuring out the kind of function to pass to it. So whatever we decide, I'd like to make sure the user gets an opportunity to write a function that they pass to `iterate`. Adding another step beforehand is fine with me. Is there an intermediate step? 

Would this make it clearer?
```clojure
(= [:foo :foo :foo :foo :foo]
   (take 5 (iterate ___ :foo))))
```

That's really my only idea for right now, so again, definitely open to suggestions if you have specific ideas on how to make it easier while still teaching the concept.

**Comment by trptcolin** [comment]
Closing for now - definitely open to looking at PRs for improvements here!

**Comment by rpazyaquian** [comment]
I'm coming back to this PR after a while and am now kicking myself for brainfarting so hard on this. Protip to those using these koans: [Grimoire](http://conj.io/) is your friend. Also, get familiar with [core](http://clojure.github.io/clojure/clojure.core-api.html).

**Comment by trptcolin** [comment]
Great tips! :+1:

**Comment by eslachance** [comment]
I know this is closed and I'm bringing this up 2 years later, but I do actually know what would make this less of a hurdle while while, I feel, not reducing the lesson's impact: make `:foo` `"foo"` because we already know how  to use `(keyword "foo")` to convert it. This is one of those places that I really had to scratch my head and look for a potential answer because of the specific limitation of "not knowing what to put in there".

Obviously it should have occured to me to pass a function there, but I wanted it simple and that didn't feel simple.

**Comment by telekid** [comment]
@eslachance haven't looked at Clojure for a while, but it sounds like you're talking about the [identity function](https://clojuredocs.org/clojure.core/identity).

**Comment by eslachance** [comment]
I... I guess that can work. What a weird name for a function that literally says "returns its arguements"? There's probably a super geeky historical reason for this but I'll be damned if any of us noob plebs would ever find that on our own. Clojure is a really weird world full of awkwardly-named methods.

**Comment by trptcolin** [comment]
Thanks for the feedback! I've made the `:hello` -> `"hello"` change you suggested, as well as passing an explicit function argument to the first `iterate` example. Hopefully that'll make this one a little easier. `iterate` is kind of a tricky one, so it's great to clarify some of this surrounding context.

And yep, `identity`, is that `(fn [x] x)`. It's kind of [a math thing](https://en.wikipedia.org/wiki/Identity_function) but yeah, discoverability is hard in general.

**Comment by Nectarineimp** [comment]
This might help your understanding:> (def x 500)#'sandbox14268/x> identity(x)#<core$identity clojure.core$identity@21c5c40f>> x500500 is the value, but the identity is something much deeper. It IS the x. 500 is just what the x represents. However the identity of x also represents 500.On October 8, 2017 at 1:24 PM Évelyne Lachance <notifications@github.com> wrote:I... I guess that can work. What a weird name for a function that literally says "returns its arguements"? There's probably a super geeky historical reason for this but I'll be damned if any of us noob plebs would ever find that on our own. Clojure is a really weird world full of awkwardly-named methods.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Nectarineimp** [comment]
Oh and here is a mind bender. Guess why these produce the answers they do:> (identical? 127 127)true> (identical? 128 128)falseThe JVM caches all 8 bit numbers. Greater than 8 bits and then it creates separate objects. See? Seems insane until you know what shit is going on under the hood.
On October 8, 2017 at 1:24 PM Évelyne Lachance <notifications@github.com> wrote:I... I guess that can work. What a weird name for a function that literally says "returns its arguements"? There's probably a super geeky historical reason for this but I'll be damned if any of us noob plebs would ever find that on our own. Clojure is a really weird world full of awkwardly-named methods.

**Comment by zackteo** [comment]
Newbie here and this got me stumped as well. 

I tried #(%) at some point only to realise I still need to know identity - #(identity %). 

Wouldn't have figured out how to do this without googling to get - (fn[x] x) or identity
