### ISSUE TITLE
koans won't run with Clojure 1.6

### ISSUE THREAD

**Issue by rubic** [functional-koans/clojure-koans#98]
I've got Clojure 1.6 installed, but the koans won't run:

```
$ clj
Clojure 1.6.0
user=> 

$ ./script/run
Exception in thread "main" java.lang.Exception: Clojure version 1.5 or higher required., compiling:(.../koans/script/run.clj:1:30)
```

**Comment by trptcolin** [comment]
Sorry for taking awhile to see this! I'm not sure what `clj` is, so that may be the issue but there are 2 options listed in the README. 

1. If you're running from a zipfile hosted on the website (the latest one from [the releases page](https://github.com/functional-koans/clojure-koans/releases)), that's when you run `./script/run`.
2. [RECOMMENDED] If you're running from a git checkout of the repository, you should run `lein koan run` instead (highly recommend installing [Leiningen](https://github.com/technomancy/leiningen)).

If you've still got this problem, I'm probably going to need more details on how to reproduce it (e.g. running from git checkout vs. zipfile, what does the `lib` directory look like, etc.). Again, sorry for taking so long to get to this.
